# Generated by Django 5.0.9 on 2024-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('answer01', models.CharField(max_length=30, null=True)),
                ('answer02', models.CharField(max_length=30, null=True)),
                ('answer03', models.CharField(max_length=30, null=True)),
                ('answer04', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
