# Generated by Django 5.0.9 on 2024-10-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('answer01', models.CharField(max_length=30, null=True)),
                ('answer02', models.CharField(max_length=30, null=True)),
                ('answer03', models.CharField(max_length=30, null=True)),
                ('answer04', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'pysc_Question',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pysc_Test',
            },
        ),
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_details', to='pysc_app.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_details', to='pysc_app.test')),
            ],
            options={
                'db_table': 'pysc_TestDetail',
                'unique_together': {('question', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('test_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_result_details', to='pysc_app.testdetail')),
            ],
            options={
                'db_table': 'pysc_TestResultDetail',
            },
        ),
    ]
