# Generated by Django 5.0.9 on 2024-10-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pysc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='pysc_Question',
        ),
        migrations.AlterModelTable(
            name='test',
            table='pysc_Test',
        ),
    ]
