# Generated by Django 5.0.9 on 2024-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysc_app', '0002_alter_question_table_alter_test_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
