# Generated by Django 5.0.9 on 2024-10-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysc_app', '0003_alter_question_id_alter_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_details', to='pysc_app.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_details', to='pysc_app.test')),
            ],
            options={
                'db_table': 'pysc_TestDetails',
                'unique_together': {('question', 'test')},
            },
        ),
    ]
