# Generated by Django 5.0.9 on 2024-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysc_app', '0004_testdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
