# Generated by Django 5.0.9 on 2024-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysc_app', '0007_alter_question_id_alter_test_id_alter_testdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
